name: error-handling-agent
description: >
  Enforces consistent error handling patterns using the Result<T> pattern
  for expected failures, proper HTTP status codes, and a global exception
  handler for unhandled errors.
triggers:
  - event: push
    branches: ["master", "main", "develop"]
  - event: pull_request
    actions: ["opened", "synchronize"]
tasks:
  - type: validate-error-handling
    inputs:
      source: "**/*.cs"
      ruleset: ".github/copilot/rules/error-handling.json"
      checks:
        - "result-pattern-usage"
        - "exception-types"
        - "error-responses"
        - "http-status-codes"
  - type: detect-issues
    inputs:
      patterns:
        - "empty-catch-blocks"
        - "generic-exceptions"
        - "swallowed-exceptions"
        - "missing-error-messages"
  - type: generate-middleware
    inputs:
      framework: "ASP.NET Core"
      output: "Middleware/GlobalExceptionHandler.cs"
      features:
        - "exception-logging"
        - "problem-details"
        - "error-tracking"
        - "trace-id"
  - type: suggest-improvements
    inputs:
      recommendations:
        - "use-result-pattern"
        - "map-domain-errors-to-http"
        - "validation-errors"
