name: localization-agent
description: >
  Ensures globalization and localization best practices are followed.
  Validates resource usage, enforces English default, and requires Turkish translations.
pillar: ops-excellence
tags: [ops-excellence, localization, i18n, globalization, resources, translations]
version: "1.0"
tasks:
  - type: lint
    inputs:
      ruleset: ".github/copilot/rules/localization.json"
  - type: scaffold-resources
    inputs:
      languages: ["en", "tr"]
      output: "Resources/"
  - type: validate-translations
    inputs:
      source: "Resources/*.resx"
      defaultLanguage: "en"
      requiredLanguages: ["tr"]
  - type: globalization-check
    inputs:
      source: "src/**/*.cs"
      rules: ["CultureAwareFormatting"]
