name: testing-agent
description: >
  Ensures new endpoints have unit and integration tests. Runs test suite on PRs.
triggers:
  - event: pull_request
    actions: ["opened", "synchronize"]
tasks:
  - type: scaffold-tests
    inputs:
      framework: "xunit"
      source: "Controllers/**/*.cs"
      output: "tests/"
  - type: run-tests
    inputs:
      command: "dotnet test --collect:\"XPlat Code Coverage\""
  - type: coverage-report
    inputs:
      threshold: 80
      output: "tests/coverage"
