name: Build, Test, and Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DOTNET_VERSION: '9.0.x'
  BUILD_CONFIGURATION: 'Release'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore ProductApi.csproj
    
    - name: Build
      run: dotnet build ProductApi.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: bin/${{ env.BUILD_CONFIGURATION }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore ProductApi.csproj
    
    - name: Run tests
      run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }} --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: coverage
    
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        format: markdown
        output: both

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security scan
      uses: securego/gosec@master
      continue-on-error: true
    
    - name: Dependency Check
      run: dotnet list package --vulnerable --include-transitive

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
    
    - name: Deploy to Azure Web App
      # Uncomment and configure when ready to deploy
      # uses: azure/webapps-deploy@v2
      # with:
      #   app-name: your-app-name
      #   publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      run: echo "Deploy step - configure your deployment target"
